# Configurações para Streamlit Cloud
[general]
SECRET_KEY = "your-production-secret-key-here-minimum-32-characters-long"
DATABASE_URL = "sqlite:///./cvmaker.db"
DEBUG = false
ACCESS_TOKEN_EXPIRE_MINUTES = 30
API_V1_PREFIX = "/api/v1"
ALGORITHM = "HS256"

# Para deploy local, usar localhost
# Para deploy em produção, será configurado via Streamlit Cloud interface
API_BASE_URL = "http://localhost:8000/api/v1"

[database]
# SQLite para simplicidade no deploy gratuito
url = "sqlite:///./cvmaker.db"

[nlp]
spacy_model = "pt_core_news_sm"

[storage]
pdf_path = "./storage/pdfs"
log_path = "./storage/logs"
